#pragma once

namespace ehm_dal::schema {
// Club record indexes
/*!
 * \brief The ClubRecordIndex enum represents the types/row numbers for club records
 */
enum ClubRecordIndex {
    // Club records
    CLUB_MOST_POINTS = 0,
    CLUB_WINS,
    CLUB_LOSSES,
    CLUB_GOALS_SCORED,
    CLUB_GOALS_AGAINST,
    CLUB_LEAST_POINTS,
    CLUB_TIES,
    // Player records
    PLAYER_SEASON_GOALS,
    PLAYER_SEASON_ASSISTS,
    PLAYER_SEASON_POINTS,
    PLAYER_SEASON_PENALTY_MINUTES,
    PLAYER_SEASON_WINS,
    PLAYER_SEASON_SHUTOUTS,
    PLAYER_ROOKIE_SEASON_POINTS,
    PLAYER_ROOKIE_SEASON_GOALS,
    PLAYER_ROOKIE_SEASON_ASSISTS,
    PLAYER_CAREER_GAMES,
    PLAYER_CAREER_GOALS,
    PLAYER_CAREER_ASSISTS,
    PLAYER_CAREER_POINTS,
    PLAYER_CAREER_PENALTY_MINUTES,
    PLAYER_CAREER_WINS,
    PLAYER_CAREER_SHUTOUTS,
    TOTAL_CLUB_RECORDS_COUNT,
    FIRST_CLUB_RECORD_ITEM = CLUB_MOST_POINTS,
    LAST_CLUB_RECORD_ITEM = CLUB_TIES,
    CLUB_RECORD_ITEM_COUNT = (LAST_CLUB_RECORD_ITEM - FIRST_CLUB_RECORD_ITEM) + 1,
    FIRST_PLAYER_RECORD_ITEM = PLAYER_SEASON_GOALS,
    LAST_PLAYER_RECORD_ITEM = PLAYER_CAREER_SHUTOUTS,
    PLAYER_RECORD_ITEM_COUNT = (LAST_PLAYER_RECORD_ITEM - FIRST_PLAYER_RECORD_ITEM) + 1
};
}; // namespace ehm_dal::schema
